namespace: thatsmidnight
name: homelab
version: 1.0.0
readme: README.md
authors:
  - "thatsmidnight <thatsmidnight@thatsmidnight.com>"
description: >-
  A comprehensive collection of Ansible roles for deploying and managing
  homelab infrastructure including Docker, Swarm, Portainer, Pi-hole, and more.
license:
  - "CC0-1.0"
tags:
  - homelab
  - docker
  - infrastructure
  - automation
  - selfhosted
dependencies: {}
repository: "https://github.com/thatsmidnight/Homelab-Ansible"
documentation: "https://github.com/thatsmidnight/Homelab-Ansible/blob/main/README.md"
homepage: "https://github.com/thatsmidnight/Homelab-Ansible"
issues: "https://github.com/thatsmidnight/Homelab-Ansible/issues"
build_ignore:
  - .git
  - .gitignore
  - .ansible
  - '*.pyc'
  - '*.pyo'
  - '.DS_Store'
  - '.vscode'
  - 'tests/'
  - '*.tar.gz'
