---
# Simple SSH connectivity test without vault dependencies
- name: Test SSH connectivity
  hosts: all
  gather_facts: false
  tasks:
    - name: Simple ping test
      ansible.builtin.ping:
      
    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname_result
      
    - name: Display hostname
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} reports hostname: {{ hostname_result.stdout }}"
