---
# Default variables for portainer role
# Deployment mode
portainer_mode: swarm  # swarm or standalone

# Container configuration
portainer_image: portainer/portainer-ce:latest
portainer_container_name: portainer
portainer_data_volume: portainer_data

# Network configuration
portainer_http_port: 8000
portainer_https_port: 9443
portainer_edge_port: 8000

# Admin configuration
portainer_admin_user: admin
portainer_admin_password: "changeme"  # Default fallback only
portainer_admin_password_file: /tmp/portainer_password

# Agent configuration
portainer_agent_enabled: true
portainer_agent_image: portainer/agent:latest
portainer_agent_secret: ""  # Default empty

# SSL configuration
portainer_ssl_enabled: false
portainer_ssl_cert_path: ""
portainer_ssl_key_path: ""

# Health check configuration
portainer_health_check_enabled: true
portainer_health_check_timeout: 120
portainer_health_check_retries: 12
