---
# Portainer Swarm deployment tasks
- name: Deploy Portainer as Docker Swarm service with retry logic
  community.docker.docker_swarm_service:
    hostname: "{{ portainer_container_name }}_{{ portainer_container_name }}"
    name: "{{ portainer_container_name }}_{{ portainer_container_name }}"
    image: "{{ portainer_image }}"
    publish:
      - published_port: "{{ portainer_http_port }}"
        target_port: 8000
        protocol: tcp
      - published_port: "{{ portainer_https_port }}"
        target_port: 9443
        protocol: tcp
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - source: "{{ portainer_data_volume }}"
        target: /data
        type: volume
    env:
      - "PORTAINER_ADMIN_PASSWORD_FILE={{ portainer_admin_password_file }}"
    placement:
      constraints:
        - node.role == manager
    state: present
  register: portainer_deployment
  retries: 3
  delay: 30
  until: portainer_deployment is succeeded
