---
# Portainer standalone deployment tasks
- name: Deploy Portainer as standalone container
  community.docker.docker_container:
    name: "{{ portainer_container_name }}"
    image: "{{ portainer_image }}"
    ports:
      - "{{ portainer_http_port }}:8000"
      - "{{ portainer_https_port }}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ portainer_data_volume }}:/data"
    env:
      PORTAINER_ADMIN_PASSWORD_FILE: "{{ portainer_admin_password_file }}"
    restart_policy: unless-stopped
    state: started
  register: portainer_container_result
