---
# Portainer health check tasks
- name: Verify Portainer container is running
  community.docker.docker_container_info:
    name: "{{ portainer_container_name }}"
  register: portainer_container_info
  when: portainer_mode == 'standalone'

- name: Verify Portainer service is running
  ansible.builtin.shell: docker service ls --filter name={{ portainer_container_name }}_{{ portainer_container_name }} --format "{% raw %}{{.Replicas}}{% endraw %}"
  register: portainer_service_info
  changed_when: false
  when: portainer_mode == 'swarm'

- name: Handle Portainer deployment failure
  block:
    - name: Get Portainer service logs (Swarm mode)
      ansible.builtin.shell: docker service logs {{ portainer_container_name }}_{{ portainer_container_name }} --tail 50
      register: portainer_logs
      when: portainer_mode == 'swarm'
      
    - name: Get Portainer container logs (Standalone mode)
      ansible.builtin.shell: docker logs {{ portainer_container_name }} --tail 50
      register: portainer_logs
      when: portainer_mode == 'standalone'
      
    - name: Display failure information
      ansible.builtin.debug:
        msg: |
          Portainer deployment failed. Service logs:
          {{ portainer_logs.stdout_lines | join('\n') }}
          
    - name: Clean up failed deployment (Swarm mode)
      community.docker.docker_swarm_service:
        name: "{{ portainer_container_name }}_{{ portainer_container_name }}"
        state: absent
      when: portainer_mode == 'swarm'
      
    - name: Clean up failed deployment (Standalone mode)
      community.docker.docker_container:
        name: "{{ portainer_container_name }}"
        state: absent
      when: portainer_mode == 'standalone'
        
    - name: Fail with helpful message
      ansible.builtin.fail:
        msg: "Portainer deployment failed. Check logs above for details."
  when: 
    - (portainer_mode == 'swarm' and portainer_service_info.stdout != '1/1') or
      (portainer_mode == 'standalone' and not portainer_container_info.container.State.Running)

- name: Display Portainer access information
  ansible.builtin.debug:
    msg: |
      ✅ Portainer is running successfully!
      Web Interface: https://{{ ansible_host }}:{{ portainer_https_port }}
      Username: {{ portainer_admin_user }}
      Mode: {{ portainer_mode }}
