---
# Portainer role main tasks
- name: Include validation tasks
  ansible.builtin.include_tasks: validate.yml
  tags: [portainer, validate]

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags: [portainer, setup]

- name: Include deployment tasks (Swarm mode)
  ansible.builtin.include_tasks: deploy_swarm.yml
  when: portainer_mode == 'swarm'
  tags: [portainer, deploy, swarm]

- name: Include deployment tasks (Standalone mode)
  ansible.builtin.include_tasks: deploy_standalone.yml
  when: portainer_mode == 'standalone'
  tags: [portainer, deploy, standalone]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: [portainer, configure]

- name: Include agent deployment tasks
  ansible.builtin.include_tasks: agents.yml
  when: portainer_agent_enabled and portainer_mode == 'swarm'
  tags: [portainer, agents]

- name: Include health check tasks
  ansible.builtin.include_tasks: health_check.yml
  when: portainer_health_check_enabled
  tags: [portainer, health]
