---
# Portainer setup tasks
- name: Install PyYAML for Docker Compose operations
  ansible.builtin.apt:
    name: python3-yaml
    state: present
    update_cache: true

- name: Create Portainer data volume
  community.docker.docker_volume:
    name: "{{ portainer_data_volume }}"
    state: present

- name: Check if Portainer is already configured
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:{{ portainer_https_port }}/api/status"
    validate_certs: false
  register: portainer_status
  failed_when: false
  changed_when: false

- name: Create Portainer admin password file
  ansible.builtin.copy:
    content: "{{ portainer_admin_password }}"
    dest: "{{ portainer_admin_password_file }}"
    mode: '0600'
    owner: root
    group: root
  when: portainer_status.status != 200
