---
# Validation tasks for portainer role
- name: Validate Portainer configuration
  ansible.builtin.assert:
    that:
      - portainer_mode in ['swarm', 'standalone']
      - portainer_admin_password is defined
      - portainer_admin_password != "changeme"
      - portainer_admin_password | length >= 8
      - portainer_image is defined
    fail_msg: |
      Portainer role configuration is invalid:
      - portainer_mode must be 'swarm' or 'standalone'
      - portainer_admin_password must be defined and at least 8 characters
      - portainer_admin_password cannot be the default 'changeme'
      - portainer_image must be defined
    success_msg: "Portainer role configuration is valid"

- name: Validate Docker is running
  ansible.builtin.command: docker system info
  register: docker_status
  changed_when: false
  failed_when: docker_status.rc != 0
