---
# Docker Swarm manager tasks
- name: Check current Docker Swarm status
  ansible.builtin.shell: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
  register: current_swarm_state
  changed_when: false

- name: Initialize Docker Swarm (first manager only)
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
    listen_addr: "{{ docker_swarm_listen_addr }}"
  register: swarm_info
  when: 
    - current_swarm_state.stdout != "active"
    - inventory_hostname == groups['manager_nodes'][0] | default(inventory_hostname)
    - groups['manager_nodes'] is defined

- name: Get manager join token
  ansible.builtin.command: docker swarm join-token -q manager
  register: manager_join_token
  changed_when: false
  delegate_to: "{{ groups['manager_nodes'][0] | default(inventory_hostname) }}"
  when: 
    - groups['manager_nodes'] is defined
    - groups['manager_nodes'] | length > 1

- name: Join additional managers to swarm
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
    join_token: "{{ manager_join_token.stdout }}"
    remote_addrs: 
      - "{{ hostvars[groups['manager_nodes'][0]]['ansible_default_ipv4']['address'] }}"
  when:
    - current_swarm_state.stdout != "active"
    - inventory_hostname != groups['manager_nodes'][0] | default(inventory_hostname)
    - groups['manager_nodes'] is defined
    - groups['manager_nodes'] | length > 1

- name: Display Swarm status
  ansible.builtin.debug:
    msg: "Swarm manager {{ inventory_hostname }} is active"
