---
# Validation tasks for docker_swarm role
- name: Validate Docker Swarm configuration
  ansible.builtin.assert:
    that:
      - docker_swarm_role in ['manager', 'worker']
      - docker_swarm_advertise_addr is defined
    fail_msg: "Docker Swarm role configuration is invalid"
    success_msg: "Docker Swarm role configuration is valid"

- name: Validate Docker is installed
  ansible.builtin.command: docker --version
  register: docker_version_check
  changed_when: false
  failed_when: docker_version_check.rc != 0
