---
# Minimal setup - just Docker and Portainer
- name: Minimal homelab setup
  hosts: homelab_server
  become: true
  vars_files:
    - ../../vars.yml
    - ../../vault.yml
  roles:
    - role: common
      tags: [common, base]
      
    - role: docker
      tags: [docker, containers]
      
    - role: portainer
      vars:
        portainer_mode: standalone
      tags: [portainer, management]

  post_tasks:
    - name: Display minimal setup completion
      ansible.builtin.debug:
        msg: |
          ✅ Minimal homelab setup completed!
          
          Services available:
          - Portainer: https://{{ ansible_host }}:9443
