---
# Single node homelab deployment
- name: Deploy homelab on single node
  hosts: homelab_server
  become: true
  vars_files:
    - ../../vars.yml
    - ../../vault.yml
  roles:
    - role: common
      vars:
        common_admin_user: "{{ admin_user }}"
        common_admin_email: "{{ admin_email }}"
        common_admin_password: "{{ admin_password }}"
        common_admin_ssh_key: "{{ admin_ssh_key_public }}"
      tags: [common, base]
      
    - role: docker
      vars:
        docker_users:
          - "{{ admin_user }}"
      tags: [docker, containers]
      
    - role: portainer
      vars:
        portainer_mode: standalone
        # portainer_admin_password will be inherited from vars.yml
      tags: [portainer, management]
      
    - role: pihole
      vars:
        # pihole_web_password will be inherited from vars.yml
      tags: [pihole, dns]

  post_tasks:
    - name: Display single-node deployment completion
      ansible.builtin.debug:
        msg: |
          🎉 Single-node homelab deployment completed!
          
          Services available:
          - Portainer: https://{{ ansible_host }}:9443
          - Pi-hole: http://{{ ansible_host }}:8081/admin
