---
# Docker health check tasks
- name: Check Docker daemon health
  ansible.builtin.command: docker system info
  register: docker_health
  changed_when: false
  failed_when: docker_health.rc != 0

- name: Verify Docker version
  ansible.builtin.command: docker --version
  register: docker_version_check
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    msg: "Docker version: {{ docker_version_check.stdout }}"

- name: Test Docker functionality
  community.docker.docker_container:
    name: docker_health_test
    image: hello-world
    state: started
    detach: false
    cleanup: true
  register: docker_test_result

- name: Display Docker test result
  ansible.builtin.debug:
    msg: "Docker test completed successfully"
  when: docker_test_result is succeeded
