---
# Validation tasks for docker role
- name: Validate Docker configuration
  ansible.builtin.assert:
    that:
      - docker_users is defined and docker_users | length > 0
      - docker_packages is defined and docker_packages | length > 0
    fail_msg: "Docker role configuration is invalid"
    success_msg: "Docker role configuration is valid"

- name: Check if system is supported
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Debian']
      - ansible_architecture in ['x86_64', 'aarch64', 'arm64']
    fail_msg: "Unsupported OS or architecture: {{ ansible_distribution }} {{ ansible_architecture }}"
    success_msg: "System is supported for Docker installation"
