---
# Main site playbook - complete homelab deployment
- name: Deploy complete homelab infrastructure
  import_playbook: examples/multi-node-homelab.yml

- name: Verify deployment health
  hosts: all
  become: true
  vars_files:
    - ../vars.yml
    - ../vault.yml
  tasks:
    - name: Verify Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
      tags: [health, verify]

    - name: Check Docker Swarm status
      ansible.builtin.shell: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
      register: swarm_status
      changed_when: false
      failed_when: false
      tags: [health, verify]

    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          🎉 Homelab deployment completed successfully!
          
          Services deployed:
          - Docker Engine: ✅ Running
          - Docker Swarm: {{ 'Active' if swarm_status.stdout == 'active' else 'Not configured' }}
          - Portainer: Check http://{{ ansible_default_ipv4.address }}:9000
          - Pi-hole: Check http://{{ ansible_default_ipv4.address }}:8080
      tags: [health, verify]
