---
# Pi-hole deployment tasks
- name: Create Pi-hole data directory
  ansible.builtin.file:
    path: "{{ pihole_data_path }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Deploy Pi-hole using Docker Compose
  community.docker.docker_compose_v2:
    project_name: pihole-stack
    definition: "{{ lookup('template', 'pihole-compose.yml.j2') | from_yaml }}"
    state: present
    remove_orphans: true
  register: pihole_deployment

- name: Wait for Pi-hole container to be ready
  ansible.builtin.wait_for:
    port: "{{ pihole_web_port }}"
    host: "{{ ansible_host }}"
    delay: 15
    timeout: 300

- name: Display deployment result
  ansible.builtin.debug:
    msg: "Pi-hole deployed successfully"
  when: pihole_deployment is succeeded
