---
# Validation tasks for pihole role
- name: Validate Pi-hole configuration
  ansible.builtin.assert:
    that:
      - pihole_web_password is defined
      - pihole_web_password != "changeme"
      - pihole_web_password | length >= 8
      - pihole_image is defined
      - pihole_dns_port is defined and pihole_dns_port | int > 0
    fail_msg: |
      Pi-hole role configuration is invalid:
      - pihole_web_password must be defined and at least 8 characters
      - pihole_web_password cannot be the default 'changeme'
      - pihole_image must be defined
      - pihole_dns_port must be a positive integer
    success_msg: "Pi-hole role configuration is valid"

- name: Validate Docker is running
  ansible.builtin.command: docker system info
  register: docker_status
  changed_when: false
  failed_when: docker_status.rc != 0

- name: Check for port conflicts
  ansible.builtin.shell: netstat -tuln | grep ":{{ pihole_dns_port }}"
  register: port_check
  failed_when: false
  changed_when: false

- name: Warn about potential port conflicts
  ansible.builtin.debug:
    msg: "Warning: Port {{ pihole_dns_port }} is already in use. Pi-hole may fail to start."
  when: port_check.rc == 0
